#!/usr/bin/env bash
set -euo pipefail

# Usage: ./create-server.sh SERVER_ID DISPLAY_NAME SLUG TYPE VERSION GAME_PORT RCON_PORT MEMORY_MB [SEED] [OPS_JSON] [ADDONS_JSON] [MAX_PLAYERS] [GAMEMODE] [WHITELIST] [DIFFICULTY] [WORLD_TYPE] [WHITELIST_PLAYERS_JSON]

if [ "$#" -lt 8 ]; then
  echo "Usage: $0 SERVER_ID DISPLAY_NAME SLUG TYPE VERSION GAME_PORT RCON_PORT MEMORY_MB [SEED] [OPS_JSON] [ADDONS_JSON] [MAX_PLAYERS] [GAMEMODE] [WHITELIST] [DIFFICULTY] [WORLD_TYPE] [WHITELIST_PLAYERS_JSON]"
  exit 1
fi

SERVER_ID="$1"
DISPLAY_NAME="$2"
SLUG="$3"
TYPE="$4"
VERSION="$5"
GAME_PORT="$6"
RCON_PORT="$7"
MEMORY_MB="$8"
SEED="${9:-}"
OPS="${10:-[]}"
ADDONS="${11:-[]}"
MAX_PLAYERS="${12:-20}"
GAMEMODE="${13:-survival}"
WHITELIST="${14:-false}"
DIFFICULTY="${15:-normal}"
WORLD_TYPE_RAW="${16:-default}"
WHITELIST_PLAYERS="${17:-[]}"

# Map UI world types to Minecraft 1.18+ level-type values
case "$WORLD_TYPE_RAW" in
  flat)       LEVEL_TYPE="minecraft:flat" ;;
  large_biomes) LEVEL_TYPE="minecraft:large_biomes" ;;
  amplified)  LEVEL_TYPE="minecraft:amplified" ;;
  *)          LEVEL_TYPE="minecraft:normal" ;;
esac

# Shared jar validation helper (B-8)
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/jar-utils.sh"

BASE="/home/ubuntu/omricraft"
SERVERS_DIR="$BASE/servers"
SERVER_DIR="$SERVERS_DIR/$SERVER_ID"
TEMPLATE_JAR="$BASE/templates/paper/server.jar"
SERVERS_JSON="$BASE/manager/servers.json"
FORWARDING_SECRET_FILE="$BASE/velocity/forwarding.secret"

echo "[$(date)] Creating server $SERVER_ID (slug: $SLUG, port: $GAME_PORT, version: $VERSION)..."

if ! echo "$SERVER_ID" | grep -qE '^[a-z0-9_-]+$'; then
  echo "[$(date)] ERROR: SERVER_ID '$SERVER_ID' contains invalid characters."
  exit 1
fi

if ! echo "$SLUG" | grep -qE '^[a-z0-9_-]+$'; then
  echo "[$(date)] ERROR: SLUG '$SLUG' contains invalid characters."
  exit 1
fi

if [ ! -f "$FORWARDING_SECRET_FILE" ]; then
  echo "[$(date)] ERROR: forwarding.secret not found."
  exit 1
fi

FORWARDING_SECRET=$(cat "$FORWARDING_SECRET_FILE")

mkdir -p "$SERVER_DIR/logs" "$SERVER_DIR/plugins" "$SERVER_DIR/mods" "$SERVER_DIR/config"

# Jar download is delegated to download-server-jar.sh — the SINGLE source of
# truth for per-type jar download (also used by manager-api /change-version).
# It downloads to $SERVER_DIR/server.jar (or installs the mod loader) with
# 0-byte checks and FAIL-LOUD behaviour. Do not inline jar logic here.
SCRIPTS_DIR_SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bash "$SCRIPTS_DIR_SELF/download-server-jar.sh" "$SERVER_DIR" "$TYPE" "$VERSION"

# Default plugins for Bukkit-family (Paper/Purpur/Folia/Mohist): ONLY PlasmoVoice.
# EssentialsX/LuckPerms are NOT auto-installed — they pin to a build that breaks on
# newer MC versions (e.g. 26.x); users opt in via the panel. Via* live on the proxy.
if [ "$TYPE" != "fabric" ] && [ "$TYPE" != "forge" ] && [ "$TYPE" != "neoforge" ]; then
  if [ -d "$BASE/templates/plugins" ]; then
    cp "$BASE/templates/plugins"/PlasmoVoice*.jar "$SERVER_DIR/plugins/" 2>/dev/null || true
    echo "[$(date)] Default plugin (PlasmoVoice) copied."
  fi
fi

echo "eula=true" > "$SERVER_DIR/eula.txt"

RCON_PASS=$(cat /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 16 || true)
[ -z "$RCON_PASS" ] && RCON_PASS=$(openssl rand -hex 8)

cat > "$SERVER_DIR/server.properties" <<PROPS
server-port=${GAME_PORT}
server-ip=127.0.0.1
enable-rcon=true
rcon.port=${RCON_PORT}
rcon.password=${RCON_PASS}
online-mode=false
enforce-secure-profile=false
level-name=world
level-seed=${SEED}
level-type=${LEVEL_TYPE}
motd=${DISPLAY_NAME}
max-players=${MAX_PLAYERS}
difficulty=${DIFFICULTY}
gamemode=${GAMEMODE}
white-list=${WHITELIST}
spawn-protection=16
enable-command-block=false
PROPS

# server.properties holds the RCON password — restrict to owner only (not world/group readable).
chmod 600 "$SERVER_DIR/server.properties"

mkdir -p "$SERVER_DIR/config"
cat > "$SERVER_DIR/config/paper-global.yml" <<PAPERCONF
_version: 28
proxies:
  bungee-cord:
    online-mode: false
  velocity:
    enabled: true
    online-mode: true
    secret: '${FORWARDING_SECRET}'
PAPERCONF

# spigot.yml — explicitly DISABLE legacy BungeeCord forwarding. We use Velocity
# MODERN forwarding (configured in paper-global.yml above). Having both enabled
# is a config conflict that breaks player-info forwarding. Paper's default is
# already false, but we write it explicitly so the born-correct guarantee does
# not depend on Paper's first-run defaults.
cat > "$SERVER_DIR/spigot.yml" <<'SPIGOTCONF'
# This file is auto-generated by create-server.sh (born-correct config).
settings:
  bungeecord: false
SPIGOTCONF

# Generate ops.json if ops provided
if [ -n "$OPS" ] && [ "$OPS" != "[]" ]; then
  node -e "
    const names = JSON.parse(process.argv[1]);
    const ops = names.map(function(n){ return {uuid:'',name:n,level:4,bypassesPlayerLimit:false}; });
    require('fs').writeFileSync(process.argv[2], JSON.stringify(ops, null, 2));
  " "$OPS" "$SERVER_DIR/ops.json" && echo "[$(date)] ops.json written" || echo "[$(date)] Warning: could not write ops.json"
fi

# Generate whitelist.json for private servers:
# always include ops (server owners) + any explicit whitelistPlayers
if [ "$WHITELIST" = "true" ]; then
  node -e "
    const ops = JSON.parse(process.argv[1] || '[]');
    const wl  = JSON.parse(process.argv[2] || '[]');
    const all = [...new Set([...ops, ...wl])].filter(Boolean);
    const entries = all.map(function(n){ return {uuid:'',name:n}; });
    require('fs').writeFileSync(process.argv[3], JSON.stringify(entries, null, 2));
    console.log('whitelist.json: ' + all.join(', ') + ' (' + all.length + ' players)');
  " "$OPS" "$WHITELIST_PLAYERS" "$SERVER_DIR/whitelist.json" || echo "[$(date)] Warning: could not write whitelist.json"
fi

# Download mods for ALL mod-loaders (fabric/forge/neoforge) via the Modrinth API.
# No pinned URL tables: install-mod.sh resolves the newest build matching the
# server's loader+version per mod. We only map server-installable mod addonIds to
# their Modrinth slug here — client-only mods (Sodium/Iris/Litematica) are NOT
# server-installed (the panel marks them installMethod:'client'), so they are
# absent from this map and never reach create-server.sh as a server mod.
declare -A MOD_SLUGS
MOD_SLUGS["m3"]="create"             # server-required
MOD_SLUGS["m5"]="distanthorizons"    # server-optional (LOD)
MOD_SLUGS["m6"]="simple-voice-chat"  # server-optional (proximity chat)
MOD_SLUGS["m7"]="jei"                # server-optional (recipe viewer)
# m1 Sodium, m2 Iris, m4 Litematica = client-only → not server mods (see report).

if [ "$TYPE" = "fabric" ] || [ "$TYPE" = "forge" ] || [ "$TYPE" = "neoforge" ]; then
  if [ -n "$ADDONS" ] && [ "$ADDONS" != "[]" ]; then
    echo "[$(date)] Installing mods for $TYPE $VERSION..."
    # Fabric API is required by most Fabric mods — install it (matched to VERSION)
    # whenever any mod is selected for a Fabric server. install-mod.sh fails loud
    # if there is no matching build, but we don't abort the whole create over it.
    if [ "$TYPE" = "fabric" ]; then
      if bash "$SCRIPTS_DIR_SELF/install-mod.sh" "$SERVER_DIR" "$TYPE" "$VERSION" "fabric-api"; then
        echo "[$(date)] OK: fabric-api"
      else
        echo "[$(date)] WARN: could not install fabric-api for $VERSION (continuing)"
      fi
    fi
    while IFS= read -r addonId; do
      [ -z "$addonId" ] && continue
      slug="${MOD_SLUGS[$addonId]:-}"
      if [ -z "$slug" ]; then
        # Not a server-installable mod (client-only or a plugin/datapack id) — skip loudly.
        echo "[$(date)] skipped $addonId: not a server-installable mod"
        continue
      fi
      if bash "$SCRIPTS_DIR_SELF/install-mod.sh" "$SERVER_DIR" "$TYPE" "$VERSION" "$slug"; then
        echo "[$(date)] OK mod: $addonId ($slug)"
      else
        # install-mod.sh exit 2 = no compatible build for this loader+version.
        echo "[$(date)] skipped $addonId ($slug): no $TYPE build for $VERSION"
      fi
    done < <(node -e "const ids=JSON.parse(process.argv[1]); ids.forEach(function(i){console.log(i);})" "$ADDONS")
  fi
fi

# Download plugins if addons provided
declare -A PLUGIN_URLS
# --- Plugins with direct download URLs ---
PLUGIN_URLS["p1"]="https://github.com/EssentialsX/Essentials/releases/download/2.22.0/EssentialsX-2.22.0.jar"
PLUGIN_URLS["p2"]="https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot"
PLUGIN_URLS["p3"]="https://cdn.modrinth.com/data/Lu3KuzdV/versions/6W2ad1iI/CoreProtect-CE-23.2.jar"
PLUGIN_URLS["p4"]="https://cdn.modrinth.com/data/Vebnzrzj/versions/MBSY8toc/LuckPerms-Bukkit-5.5.53.jar"
PLUGIN_URLS["p5"]="https://github.com/MilkBowl/Vault/releases/download/1.7.3/Vault.jar"
PLUGIN_URLS["p6"]="https://cdn.modrinth.com/data/1u6JkXh5/versions/ecqqLKUO/worldedit-bukkit-7.3.8.jar"
PLUGIN_URLS["p9"]="https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v5.20/bluemap-5.20-paper.jar"
# TODO: Data — M5: blueMapPort not wired end-to-end. Need: App.jsx expose port field → functions pass BLUEMAP_PORT param → write to BlueMap config after plugin install
PLUGIN_URLS["p10"]="https://cdn.modrinth.com/data/FnE6S0Zk/versions/TyzRB3KW/FastLeafDecay-1.0.6.jar"
PLUGIN_URLS["p11"]="https://github.com/gecolay/GSit/releases/download/3.4.2/GSit-3.4.2.jar"
PLUGIN_URLS["p12"]="https://github.com/Multiverse/Multiverse-Core/releases/download/5.7.0/multiverse-core-5.7.0.jar"
PLUGIN_URLS["p14"]="https://github.com/PlaceholderAPI/PlaceholderAPI/releases/download/2.12.2/PlaceholderAPI-2.12.2.jar"
PLUGIN_URLS["p16"]="https://github.com/kangarko/ChatControl-Free/releases/download/5.9.6/ChatControl-Free-5.9.6.jar"
PLUGIN_URLS["p17"]="https://github.com/TownyAdvanced/Towny/releases/download/0.103.0.2/towny-0.103.0.2.jar"
PLUGIN_URLS["p19"]="https://github.com/Archy-X/AuraSkills/releases/download/2.3.12/AuraSkills-2.3.12.jar"
PLUGIN_URLS["p20"]="https://cdn.modrinth.com/data/mRfwcqe3/versions/th0S9rok/AuctionHouse-1.0.0-SNAPSHOT.jar"
PLUGIN_URLS["p22"]="https://cdn.modrinth.com/data/8fW0q2Yg/versions/nl3u6PJq/RtpGUI.jar"
PLUGIN_URLS["p23"]="https://ci.lucko.me/job/spark/lastSuccessfulBuild/artifact/spark-paper/build/libs/spark-1.10.172-paper.jar"
PLUGIN_URLS["p25"]="https://cdn.modrinth.com/data/QufNAmjx/versions/uFIoBZOK/ExcellentEnchants-5.4.1.jar"
PLUGIN_URLS["p29"]="https://cdn.modrinth.com/data/LJNGWSvH/versions/DLhBWSiW/grimac-bukkit-2.3.74-41b0fff.jar"
PLUGIN_URLS["p30"]="https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.9.1/PAPER/ViaVersion-5.9.1.jar"
PLUGIN_URLS["p32"]="https://cdn.modrinth.com/data/fALzjamp/versions/MdY6JATr/Chunky-Bukkit-1.5.3.jar"
PLUGIN_URLS["p33"]="https://hangarcdn.papermc.io/plugins/NEZNAMY/TAB/versions/5.0.7/PAPER/TAB%20v5.0.7.jar"
PLUGIN_URLS["p35"]="https://cdn.modrinth.com/data/KAaZvh09/versions/6Yb1ntAi/ClearLaggEnhanced-2026.5.3.jar"
PLUGIN_URLS["p-chatfmt"]="https://github.com/EternalCodeTeam/ChatFormatter/releases/download/v1.3.5/ChatFormatter.v1.3.5.jar"
PLUGIN_URLS["p-axiom"]="https://cdn.modrinth.com/data/evkiwA7V/versions/mSS9faHn/AxiomPaperPlugin-5.0.4-for-MC1.21.11.jar"
# ViaVersion is auto-included from templates/plugins (already installed)
PLUGIN_URLS["p-viaversion"]="https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.9.1/PAPER/ViaVersion-5.9.1.jar"

# Explicit filenames for URLs that don't end in .jar (API redirects, no extension in URL)
declare -A PLUGIN_FILENAMES
PLUGIN_FILENAMES["p2"]="Geyser-Spigot.jar"
PLUGIN_FILENAMES["p33"]="TAB.jar"

if [ "$TYPE" != "fabric" ] && [ "$TYPE" != "forge" ] && [ "$TYPE" != "neoforge" ] && [ -n "$ADDONS" ] && [ "$ADDONS" != "[]" ]; then
  echo "[$(date)] Installing plugins..."
  while IFS= read -r addonId; do
    [ -z "$addonId" ] && continue
    url="${PLUGIN_URLS[$addonId]:-}"
    if [ -n "$url" ]; then
      if [[ -n "${PLUGIN_FILENAMES[$addonId]:-}" ]]; then
        filename="${PLUGIN_FILENAMES[$addonId]}"
      else
        filename=$(basename "$url" | sed 's/\?.*$//')
      fi
      echo "[$(date)] Downloading $addonId: $filename"
      wget -q -L --timeout=60 "$url" -O "$SERVER_DIR/plugins/$filename" || true
      if validate_jar_or_fail "$SERVER_DIR/plugins/$filename" "$addonId ($filename)"; then
        echo "[$(date)] OK: $addonId ($filename)"
      else
        echo "[$(date)] FAILED (invalid jar): $addonId ($filename)"
      fi
    else
      echo "[$(date)] No URL mapped for addon: $addonId (skipping)"
    fi
  done < <(node -e "const ids=JSON.parse(process.argv[1]); ids.forEach(function(i){console.log(i);})" "$ADDONS")
fi

# Download datapacks if addons include datapacks
# d1,d4,d6,d7,d8,d9,d10,d11 = Vanilla Tweaks — require browser picker, no direct URL
# url + filename MUST stay identical to DATAPACK_CATALOG in manager-api/server.js so
# create-time installs and post-create installs land the EXACT same file.
declare -A DATAPACK_URLS
declare -A DATAPACK_FILENAMES
DATAPACK_URLS["d2"]="https://github.com/Stardust-Labs-MC/Terralith/releases/download/v2.5.9/Terralith_1.21_v2.5.9_BETA.jar"
# Minecraft only recognises a .zip (or a folder) inside world/datapacks/. A .jar is
# logged "non-pack entry, ignoring" and never loads — the archive bytes are an
# ordinary zip, only the NAME matters. Save with .zip to match the catalog.
DATAPACK_FILENAMES["d2"]="Terralith_1.21_v2.5.9_BETA.zip"
# TODO: Data — add more datapack URLs when direct download becomes available (d3 Tectonic, Nullscape, Structory)

mkdir -p "$SERVER_DIR/datapacks-pending"

if [ -n "$ADDONS" ] && [ "$ADDONS" != "[]" ]; then
  while IFS= read -r addonId; do
    [ -z "$addonId" ] && continue
    url="${DATAPACK_URLS[$addonId]:-}"
    if [ -n "$url" ]; then
      # Prefer the explicit catalog filename (.zip); fall back to URL basename.
      if [[ -n "${DATAPACK_FILENAMES[$addonId]:-}" ]]; then
        filename="${DATAPACK_FILENAMES[$addonId]}"
      else
        filename=$(basename "$url" | sed 's/\?.*$//')
      fi
      echo "[$(date)] Downloading datapack $addonId: $filename"
      wget -q -L --timeout=60 "$url" -O "$SERVER_DIR/datapacks-pending/$filename" || true
      # Datapacks are .jar/.zip archives → same ZIP-magic validation applies.
      if validate_jar_or_fail "$SERVER_DIR/datapacks-pending/$filename" "datapack $addonId"; then
        echo "[$(date)] OK datapack: $addonId ($filename)"
      else
        echo "[$(date)] FAILED (invalid archive): datapack $addonId"
      fi
    fi
  done < <(node -e "const ids=JSON.parse(process.argv[1]); ids.forEach(function(i){console.log(i);})" "$ADDONS")
fi

# Update servers.json atomically
mkdir -p "$(dirname "$SERVERS_JSON")"

NEW_ENTRY=$(cat <<ENTRY
{
  "id": "${SERVER_ID}",
  "displayName": "${DISPLAY_NAME}",
  "slug": "${SLUG}",
  "type": "${TYPE}",
  "version": "${VERSION}",
  "gamePort": ${GAME_PORT},
  "rconPort": ${RCON_PORT},
  "memoryMb": ${MEMORY_MB},
  "path": "${SERVER_DIR}",
  "publicHost": "${SLUG}.omricraft.com",
  "address": "${SLUG}.omricraft.com",
  "backendAddress": "127.0.0.1:${GAME_PORT}",
  "status": "created"
}
ENTRY
)

TMP_JSON="$SERVERS_JSON.tmp.$$"

if [ -f "$SERVERS_JSON" ]; then
  node -e "
    const fs = require('fs');
    const data = JSON.parse(fs.readFileSync('$SERVERS_JSON','utf8'));
    const arr = Array.isArray(data) ? data : (data.servers || []);
    arr.push($NEW_ENTRY);
    fs.writeFileSync('$TMP_JSON', JSON.stringify(arr, null, 2));
  "
else
  echo "[$NEW_ENTRY]" > "$TMP_JSON"
fi

mv "$TMP_JSON" "$SERVERS_JSON"

# BlueMap config — set web port based on server port (e.g. 25566 -> 26566)
BLUEMAP_PORT=$((GAME_PORT + 1000))
mkdir -p "$SERVER_DIR/plugins/BlueMap"
cat > "$SERVER_DIR/plugins/BlueMap/core.conf" << 'BLUECORE'
accept-download: true
data: "bluemap"
render-thread-count: -2
metrics: false
BLUECORE
cat > "$SERVER_DIR/plugins/BlueMap/webserver.conf" << BLUEEOF
enabled: true
webroot: "bluemap/web"
port: ${BLUEMAP_PORT}
ip: "0.0.0.0"
max-connections-per-second: 2.0
BLUEEOF
echo "[$(date)] BlueMap config written (port ${BLUEMAP_PORT})"

echo "[$(date)] Server $SERVER_ID created at $SERVER_DIR"
echo "[$(date)] Address: ${SLUG}.omricraft.com"
echo "[$(date)] Backend: 127.0.0.1:${GAME_PORT}"