#!/usr/bin/env bash
set -euo pipefail

# Usage: ./create-server.sh SERVER_ID DISPLAY_NAME SLUG TYPE VERSION GAME_PORT RCON_PORT MEMORY_MB [SEED] [OPS_JSON] [ADDONS_JSON] [MAX_PLAYERS] [GAMEMODE] [WHITELIST] [DIFFICULTY] [WORLD_TYPE] [WHITELIST_PLAYERS_JSON]

if [ "$#" -lt 8 ]; then
  echo "Usage: $0 SERVER_ID DISPLAY_NAME SLUG TYPE VERSION GAME_PORT RCON_PORT MEMORY_MB [SEED] [OPS_JSON] [ADDONS_JSON] [MAX_PLAYERS] [GAMEMODE] [WHITELIST] [DIFFICULTY] [WORLD_TYPE] [WHITELIST_PLAYERS_JSON]"
  exit 1
fi

SERVER_ID="$1"
DISPLAY_NAME="$2"
SLUG="$3"
TYPE="$4"
VERSION="$5"
GAME_PORT="$6"
RCON_PORT="$7"
MEMORY_MB="$8"
SEED="${9:-}"
OPS="${10:-[]}"
ADDONS="${11:-[]}"
MAX_PLAYERS="${12:-20}"
GAMEMODE="${13:-survival}"
WHITELIST="${14:-false}"
DIFFICULTY="${15:-normal}"
WORLD_TYPE_RAW="${16:-default}"
WHITELIST_PLAYERS="${17:-[]}"

# Map UI world types to Minecraft 1.18+ level-type values
case "$WORLD_TYPE_RAW" in
  flat)       LEVEL_TYPE="minecraft:flat" ;;
  large_biomes) LEVEL_TYPE="minecraft:large_biomes" ;;
  amplified)  LEVEL_TYPE="minecraft:amplified" ;;
  *)          LEVEL_TYPE="minecraft:normal" ;;
esac

# Shared jar validation helper (B-8)
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/jar-utils.sh"

BASE="/home/ubuntu/omricraft"
SERVERS_DIR="$BASE/servers"
SERVER_DIR="$SERVERS_DIR/$SERVER_ID"
TEMPLATE_JAR="$BASE/templates/paper/server.jar"
SERVERS_JSON="$BASE/manager/servers.json"
FORWARDING_SECRET_FILE="$BASE/velocity/forwarding.secret"

echo "[$(date)] Creating server $SERVER_ID (slug: $SLUG, port: $GAME_PORT, version: $VERSION)..."

if ! echo "$SERVER_ID" | grep -qE '^[a-z0-9_-]+$'; then
  echo "[$(date)] ERROR: SERVER_ID '$SERVER_ID' contains invalid characters."
  exit 1
fi

if ! echo "$SLUG" | grep -qE '^[a-z0-9_-]+$'; then
  echo "[$(date)] ERROR: SLUG '$SLUG' contains invalid characters."
  exit 1
fi

if [ ! -f "$FORWARDING_SECRET_FILE" ]; then
  echo "[$(date)] ERROR: forwarding.secret not found."
  exit 1
fi

FORWARDING_SECRET=$(cat "$FORWARDING_SECRET_FILE")

mkdir -p "$SERVER_DIR/logs" "$SERVER_DIR/plugins" "$SERVER_DIR/mods" "$SERVER_DIR/config"

# Jar download is delegated to download-server-jar.sh — the SINGLE source of
# truth for per-type jar download (also used by manager-api /change-version).
# It downloads to $SERVER_DIR/server.jar (or installs the mod loader) with
# 0-byte checks and FAIL-LOUD behaviour. Do not inline jar logic here.
SCRIPTS_DIR_SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bash "$SCRIPTS_DIR_SELF/download-server-jar.sh" "$SERVER_DIR" "$TYPE" "$VERSION"

# Default plugins for Bukkit-family (Paper/Purpur/Folia/Mohist/Youer): ONLY PlasmoVoice.
# EssentialsX/LuckPerms are NOT auto-installed — they pin to a build that breaks on
# newer MC versions (e.g. 26.x); users opt in via the panel. Via* live on the proxy.
if [ "$TYPE" != "fabric" ] && [ "$TYPE" != "forge" ] && [ "$TYPE" != "neoforge" ]; then
  if [ -d "$BASE/templates/plugins" ]; then
    cp "$BASE/templates/plugins"/PlasmoVoice*.jar "$SERVER_DIR/plugins/" 2>/dev/null || true
    echo "[$(date)] Default plugin (PlasmoVoice) copied."
  fi
fi

echo "eula=true" > "$SERVER_DIR/eula.txt"

RCON_PASS=$(cat /dev/urandom | tr -dc 'A-Za-z0-9' | head -c 16 || true)
[ -z "$RCON_PASS" ] && RCON_PASS=$(openssl rand -hex 8)

cat > "$SERVER_DIR/server.properties" <<PROPS
server-port=${GAME_PORT}
server-ip=127.0.0.1
enable-rcon=true
rcon.port=${RCON_PORT}
rcon.password=${RCON_PASS}
online-mode=false
enforce-secure-profile=false
level-name=world
level-seed=${SEED}
level-type=${LEVEL_TYPE}
motd=${DISPLAY_NAME}
max-players=${MAX_PLAYERS}
difficulty=${DIFFICULTY}
gamemode=${GAMEMODE}
white-list=${WHITELIST}
spawn-protection=16
enable-command-block=false
PROPS

# server.properties holds the RCON password — restrict to owner only (not world/group readable).
chmod 600 "$SERVER_DIR/server.properties"

mkdir -p "$SERVER_DIR/config"
cat > "$SERVER_DIR/config/paper-global.yml" <<PAPERCONF
_version: 28
proxies:
  bungee-cord:
    online-mode: false
  velocity:
    enabled: true
    online-mode: true
    secret: '${FORWARDING_SECRET}'
PAPERCONF

# spigot.yml — explicitly DISABLE legacy BungeeCord forwarding. We use Velocity
# MODERN forwarding (configured in paper-global.yml above). Having both enabled
# is a config conflict that breaks player-info forwarding. Paper's default is
# already false, but we write it explicitly so the born-correct guarantee does
# not depend on Paper's first-run defaults.
cat > "$SERVER_DIR/spigot.yml" <<'SPIGOTCONF'
# This file is auto-generated by create-server.sh (born-correct config).
settings:
  bungeecord: false
SPIGOTCONF

# Generate ops.json if ops provided
if [ -n "$OPS" ] && [ "$OPS" != "[]" ]; then
  node -e "
    const names = JSON.parse(process.argv[1]);
    const ops = names.map(function(n){ return {uuid:'',name:n,level:4,bypassesPlayerLimit:false}; });
    require('fs').writeFileSync(process.argv[2], JSON.stringify(ops, null, 2));
  " "$OPS" "$SERVER_DIR/ops.json" && echo "[$(date)] ops.json written" || echo "[$(date)] Warning: could not write ops.json"
fi

# Generate whitelist.json for private servers:
# always include ops (server owners) + any explicit whitelistPlayers
if [ "$WHITELIST" = "true" ]; then
  node -e "
    const ops = JSON.parse(process.argv[1] || '[]');
    const wl  = JSON.parse(process.argv[2] || '[]');
    const all = [...new Set([...ops, ...wl])].filter(Boolean);
    const entries = all.map(function(n){ return {uuid:'',name:n}; });
    require('fs').writeFileSync(process.argv[3], JSON.stringify(entries, null, 2));
    console.log('whitelist.json: ' + all.join(', ') + ' (' + all.length + ' players)');
  " "$OPS" "$WHITELIST_PLAYERS" "$SERVER_DIR/whitelist.json" || echo "[$(date)] Warning: could not write whitelist.json"
fi

# Download mods for ALL mod-loaders (fabric/forge/neoforge) via the Modrinth API.
# No pinned URL tables: install-mod.sh resolves the newest build matching the
# server's loader+version per mod. We only map server-installable mod addonIds to
# their Modrinth slug here — client-only mods (Sodium/Iris/Litematica) are NOT
# server-installed (the panel marks them installMethod:'client'), so they are
# absent from this map and never reach create-server.sh as a server mod.
declare -A MOD_SLUGS
MOD_SLUGS["m3"]="create"             # server-required
MOD_SLUGS["m5"]="distanthorizons"    # server-optional (LOD)
MOD_SLUGS["m6"]="simple-voice-chat"  # server-optional (proximity chat)
MOD_SLUGS["m7"]="jei"                # server-optional (recipe viewer)
MOD_SLUGS["m8"]="lithium"            # server perf (Fabric/NeoForge/Quilt — install-mod.sh skips loud on Forge)
MOD_SLUGS["m9"]="ferrite-core"       # server RAM optimizer
MOD_SLUGS["m10"]="c2me-fabric"       # parallel chunk gen (Fabric only — skips loud on other loaders)
MOD_SLUGS["m11"]="no-chat-reports"   # privacy
# m1 Sodium, m2 Iris, m4 Litematica, m12 Jade, m13 Xaero's, m14 ETF, m15 EMF = client-only → not server mods.

if [ "$TYPE" = "fabric" ] || [ "$TYPE" = "forge" ] || [ "$TYPE" = "neoforge" ]; then
  if [ -n "$ADDONS" ] && [ "$ADDONS" != "[]" ]; then
    echo "[$(date)] Installing mods for $TYPE $VERSION..."
    # Fabric API is required by most Fabric mods — install it (matched to VERSION)
    # whenever any mod is selected for a Fabric server. install-mod.sh fails loud
    # if there is no matching build, but we don't abort the whole create over it.
    if [ "$TYPE" = "fabric" ]; then
      if bash "$SCRIPTS_DIR_SELF/install-mod.sh" "$SERVER_DIR" "$TYPE" "$VERSION" "fabric-api"; then
        echo "[$(date)] OK: fabric-api"
      else
        echo "[$(date)] WARN: could not install fabric-api for $VERSION (continuing)"
      fi
    fi
    while IFS= read -r addonId; do
      [ -z "$addonId" ] && continue
      slug="${MOD_SLUGS[$addonId]:-}"
      if [ -z "$slug" ]; then
        # Not a server-installable mod (client-only or a plugin/datapack id) — skip loudly.
        echo "[$(date)] skipped $addonId: not a server-installable mod"
        continue
      fi
      if bash "$SCRIPTS_DIR_SELF/install-mod.sh" "$SERVER_DIR" "$TYPE" "$VERSION" "$slug"; then
        echo "[$(date)] OK mod: $addonId ($slug)"
      else
        # install-mod.sh exit 2 = no compatible build for this loader+version.
        echo "[$(date)] skipped $addonId ($slug): no $TYPE build for $VERSION"
      fi
    done < <(node -e "const ids=JSON.parse(process.argv[1]); ids.forEach(function(i){console.log(i);})" "$ADDONS")
  fi
fi

# Download plugins if addons provided — DELEGATE to install-plugin.sh, the SINGLE source
# of truth for plugin download URLs, filenames, GitHub/paid handling and the
# EssentialsXSpawn / Geyser+Floodgate companion installs. This removes the old drifted
# PLUGIN_URLS copy that used to live here and silently no-op'd several plugins at create
# time (p13/p18/p24/p31/p34 were absent from it).
if [ "$TYPE" != "fabric" ] && [ "$TYPE" != "forge" ] && [ "$TYPE" != "neoforge" ] && [ -n "$ADDONS" ] && [ "$ADDONS" != "[]" ]; then
  echo "[$(date)] Installing plugins (via install-plugin.sh — single SSOT table)..."
  while IFS= read -r addonId; do
    [ -z "$addonId" ] && continue
    # Plugin ids are p* ; mods (m*), datapacks (d*) and textures (t*) have their own loops
    # elsewhere, so only hand p* ids to install-plugin.sh.
    case "$addonId" in
      p*) ;;
      *) continue ;;
    esac
    if bash "$SCRIPTS_DIR_SELF/install-plugin.sh" "$SERVER_ID" "$addonId"; then
      echo "[$(date)] OK plugin: $addonId"
    else
      rc=$?
      if [ "$rc" -eq 2 ]; then
        echo "[$(date)] skipped plugin $addonId: premium/unavailable (cannot auto-install)"
      else
        echo "[$(date)] skipped/failed plugin $addonId (no mapped URL or download error)"
      fi
    fi
  done < <(node -e "const ids=JSON.parse(process.argv[1]); ids.forEach(function(i){console.log(i);})" "$ADDONS")
fi

# Download datapacks if addons include datapacks.
# Server-installable datapacks resolve via the Modrinth API (loader "datapack"),
# VERSION-AWARE, so the build always matches the server's MC version — pinning a
# single build (e.g. Terralith 1.21) crashed newer servers (1.21.2+ worldgen JSON
# changed). Map server-installable datapack addonIds -> Modrinth slug here.
# Vanilla Tweaks (d1,d4,d6,d7,d8,d9,d10,d11) need the browser picker (no slug) and
# are absent from this map, so they never reach create-server.sh as server installs.
declare -A DATAPACK_SLUGS
DATAPACK_SLUGS["d2"]="terralith"                  # worldgen overhaul
DATAPACK_SLUGS["d4"]="serversleep"                # Multiplayer Sleep — one player skips the night
DATAPACK_SLUGS["d6"]="mini-blocks-datapack"       # Mini Blocks
DATAPACK_SLUGS["d7"]="better-wanderingtraders"    # Wandering Trades — improved wandering-trader offers
DATAPACK_SLUGS["d9"]="hotbarcoordinates"          # Coordinates HUD above the hotbar
DATAPACK_SLUGS["d10"]="player-drops-head"         # Player Head Drops
DATAPACK_SLUGS["d11"]="amh"                       # All Mob Heads (catalog slug 'amh'; 'mob-heads' was the wrong pack)
DATAPACK_SLUGS["d12"]="veinminer"                 # VeinMiner — break a whole ore/log vein at once
DATAPACK_SLUGS["d13"]="tectonic"                  # worldgen overhaul (terrain)
DATAPACK_SLUGS["d14"]="incendium"                 # worldgen overhaul (Nether)
DATAPACK_SLUGS["d15"]="nullscape"                 # worldgen overhaul (End)
DATAPACK_SLUGS["d16"]="explorify"                 # extra vanilla structures
DATAPACK_SLUGS["d17"]="dungeons-and-taverns"      # extra structures
# d1 Vanilla Tweaks (umbrella collection) and d8 Nether Portal Coords have NO single
# Modrinth datapack equivalent — they stay installMethod:'manual' in the UI and are
# absent from this map, so they never reach create-server.sh as server installs.

# Worldgen-overhaul datapacks REPLACE the overworld generator. They only make sense on
# a 'default' world: on flat/amplified/large_biomes they override (and contradict) the
# chosen world type, AND make the world hard-depend on the pack — remove/lose the pack
# later and the world won't load ("Overworld settings missing"). So skip them unless
# the world type is 'default'.
declare -A WORLDGEN_DATAPACKS
WORLDGEN_DATAPACKS["d2"]=1
WORLDGEN_DATAPACKS["d13"]=1   # Tectonic — overworld terrain overhaul
WORLDGEN_DATAPACKS["d14"]=1   # Incendium — Nether overhaul
WORLDGEN_DATAPACKS["d15"]=1   # Nullscape — End overhaul

mkdir -p "$SERVER_DIR/datapacks-pending"

if [ -n "$ADDONS" ] && [ "$ADDONS" != "[]" ]; then
  while IFS= read -r addonId; do
    [ -z "$addonId" ] && continue
    slug="${DATAPACK_SLUGS[$addonId]:-}"
    [ -z "$slug" ] && continue
    if [ -n "${WORLDGEN_DATAPACKS[$addonId]:-}" ] && [ "$WORLD_TYPE_RAW" != "default" ]; then
      echo "[$(date)] skipped datapack $addonId ($slug): worldgen overhaul is incompatible with a '$WORLD_TYPE_RAW' world (it would override the chosen world type). Pick a 'default' world to use $slug."
      continue
    fi
    # Stage into datapacks-pending; start-server.sh drains it into world/datapacks
    # and RCON-enables on boot (pending convention kept intact).
    if bash "$SCRIPTS_DIR_SELF/install-datapack.sh" "$SERVER_DIR" "$VERSION" "$slug" pending; then
      echo "[$(date)] OK datapack: $addonId ($slug)"
    else
      rc=$?
      if [ "$rc" -eq 2 ]; then
        # No compatible build for this MC version — skip loudly. Do NOT fall back
        # to an incompatible pinned zip (that is exactly what crashed the server).
        echo "[$(date)] skipped datapack $addonId: no build for $VERSION"
      else
        echo "[$(date)] FAILED datapack: $addonId ($slug)"
      fi
    fi
  done < <(node -e "const ids=JSON.parse(process.argv[1]); ids.forEach(function(i){console.log(i);})" "$ADDONS")
fi

# Install a server-forced resource pack (texture) if a texture addon is selected.
# server.properties supports exactly ONE resource-pack, so if multiple textures are
# selected the LAST one wins. install-resourcepack.sh resolves the pack's direct
# cdn.modrinth.com URL + sha1 (version-aware) and writes resource-pack /
# resource-pack-sha1 / require-resource-pack=false into the server.properties we
# already wrote above. Map server-installable texture addonIds -> Modrinth slug here.
# t2 Golden Pumpkin Pie and t8 Shulker Box Tooltip have no server-forced equivalent
# (t8 is a client-side tooltip mod) — they stay installMethod:'client' and are absent.
declare -A TEXTURE_SLUGS
TEXTURE_SLUGS["t1"]="elibruhs-custom-hats-pack"   # Custom Hats (renamed carved pumpkins)
TEXTURE_SLUGS["t3"]="fresh-animations"            # Fresh Animations
TEXTURE_SLUGS["t4"]="faithful-32x"                # Faithful 32x
TEXTURE_SLUGS["t5"]="bare-bones"                  # Bare Bones
TEXTURE_SLUGS["t6"]="visible-ores"                # Visible Ores
TEXTURE_SLUGS["t7"]="mandalas-gui-dark-mode"      # Dark UI
TEXTURE_SLUGS["t9"]="better-leaves"               # Motschen's Better Leaves
TEXTURE_SLUGS["t10"]="dramatic-skys"              # Dramatic Skys
TEXTURE_SLUGS["t11"]="default-dark-mode"          # Default Dark Mode
TEXTURE_SLUGS["t12"]="new-glowing-ores"           # New Glowing Ores
TEXTURE_SLUGS["t13"]="glowing-glints"             # Enchantment Outlines
TEXTURE_SLUGS["t14"]="low-on-fire"                # Low On Fire

# Plugin-bound resource packs need a backing plugin (e.g. an item-model handler) to
# inject their items — they only work on a plugin-capable Bukkit-family core. On a
# vanilla/fabric/forge/neoforge core the items can never be injected, so the pack would
# be a silent no-op. The frontend already gates this (isPluginBoundBlocked), but mirror
# the worldgen safety net here so the install stays honest even if the UI is bypassed.
# Bukkit-family list matches server.js BUKKIT_TYPES.
declare -A PLUGIN_BOUND_TEXTURES
PLUGIN_BOUND_TEXTURES["t1"]=1   # Custom Hats — needs a backing plugin to apply the hats
is_bukkit_family() {
  case "$1" in
    paper|purpur|folia|mohist|youer|spigot) return 0 ;;
    *) return 1 ;;
  esac
}

if [ -n "$ADDONS" ] && [ "$ADDONS" != "[]" ]; then
  while IFS= read -r addonId; do
    [ -z "$addonId" ] && continue
    rpslug="${TEXTURE_SLUGS[$addonId]:-}"
    [ -z "$rpslug" ] && continue
    if [ -n "${PLUGIN_BOUND_TEXTURES[$addonId]:-}" ] && ! is_bukkit_family "$TYPE"; then
      echo "[$(date)] skipped resourcepack $addonId ($rpslug): plugin-bound pack needs a plugin-capable core; '$TYPE' has no backing plugin to inject the items."
      continue
    fi
    if bash "$SCRIPTS_DIR_SELF/install-resourcepack.sh" "$SERVER_DIR" "$VERSION" "$rpslug"; then
      echo "[$(date)] OK resourcepack: $addonId ($rpslug)"
    else
      rc=$?
      if [ "$rc" -eq 2 ]; then
        echo "[$(date)] skipped resourcepack $addonId ($rpslug): no build for $VERSION"
      else
        echo "[$(date)] FAILED resourcepack: $addonId ($rpslug)"
      fi
    fi
  done < <(node -e "const ids=JSON.parse(process.argv[1]); ids.forEach(function(i){console.log(i);})" "$ADDONS")
fi

# Update servers.json atomically
mkdir -p "$(dirname "$SERVERS_JSON")"

NEW_ENTRY=$(cat <<ENTRY
{
  "id": "${SERVER_ID}",
  "displayName": "${DISPLAY_NAME}",
  "slug": "${SLUG}",
  "type": "${TYPE}",
  "version": "${VERSION}",
  "gamePort": ${GAME_PORT},
  "rconPort": ${RCON_PORT},
  "memoryMb": ${MEMORY_MB},
  "path": "${SERVER_DIR}",
  "publicHost": "${SLUG}.omricraft.com",
  "address": "${SLUG}.omricraft.com",
  "backendAddress": "127.0.0.1:${GAME_PORT}",
  "status": "created"
}
ENTRY
)

TMP_JSON="$SERVERS_JSON.tmp.$$"

if [ -f "$SERVERS_JSON" ]; then
  node -e "
    const fs = require('fs');
    const data = JSON.parse(fs.readFileSync('$SERVERS_JSON','utf8'));
    const arr = Array.isArray(data) ? data : (data.servers || []);
    arr.push($NEW_ENTRY);
    fs.writeFileSync('$TMP_JSON', JSON.stringify(arr, null, 2));
  "
else
  echo "[$NEW_ENTRY]" > "$TMP_JSON"
fi

mv "$TMP_JSON" "$SERVERS_JSON"

# BlueMap config — set web port based on server port (e.g. 25566 -> 26566)
# TODO: Data — M5: blueMapPort not wired end-to-end. Need: App.jsx expose port field ->
# functions pass BLUEMAP_PORT param -> write to BlueMap config after plugin install.
BLUEMAP_PORT=$((GAME_PORT + 1000))
mkdir -p "$SERVER_DIR/plugins/BlueMap"
cat > "$SERVER_DIR/plugins/BlueMap/core.conf" << 'BLUECORE'
accept-download: true
data: "bluemap"
render-thread-count: -2
metrics: false
BLUECORE
cat > "$SERVER_DIR/plugins/BlueMap/webserver.conf" << BLUEEOF
enabled: true
webroot: "bluemap/web"
port: ${BLUEMAP_PORT}
ip: "0.0.0.0"
max-connections-per-second: 2.0
BLUEEOF
echo "[$(date)] BlueMap config written (port ${BLUEMAP_PORT})"

echo "[$(date)] Server $SERVER_ID created at $SERVER_DIR"
echo "[$(date)] Address: ${SLUG}.omricraft.com"
echo "[$(date)] Backend: 127.0.0.1:${GAME_PORT}"